<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaxonomyNodeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TaxonomyNodeRepository extends EntityRepository
{
    public function getDatabases($fennec_id){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('t.taxonomyNodeId', 'db.name')
            ->from('AppBundle\Entity\TaxonomyNode', 't')
            ->innerJoin('AppBundle/Entity/Db','db','t.db_id = db.db_id')
            ->where('t.fennec = db.db_id');
        $query = $qb->getQuery();
        $result = $query->getArrayResult();

//        $result = array();
//        while($row = $stm_get_taxonomy_databases->fetch(PDO::FETCH_ASSOC)){
//            $result[$row['name']] = $row['taxonomy_node_id'];
//        }
//        return $result;
    }

    public function getLineage(){

    }
}
