<?php

namespace AppBundle\Repository;

/**
 * TraitNumericalValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraitNumericalValueRepository extends \Doctrine\ORM\EntityRepository
{
}
