// Generated by CoffeeScript 1.10.0
(function() {
  importScripts('../lib/jszip.min.js');

  self.addEventListener('message', function(e) {
    var content, filename, zip;
    filename = e.data.filename;
    zip = new JSZip();
    zip.file(filename + ".biom", e.data.o1);
    zip.file(filename + "_log.json", e.data.o2);
    content = zip.generate({
      type: "blob"
    });
    return self.postMessage(content);
  });

}).call(this);
