// Generated by CoffeeScript 1.10.0
(function() {
  importScripts('../lib/md5.js');

  self.addEventListener('message', function(e) {
    var data, output;
    data = e.data;
    output = CryptoJS.MD5(data).toString();
    return self.postMessage(output);
  });

}).call(this);
