// Generated by CoffeeScript 1.10.0
(function() {
  importScripts('../lib/lz-string-1.3.3.js');

  self.addEventListener('message', function(e) {
    var out;
    out = LZString.decompressFromBase64(e.data);
    return self.postMessage(out);
  });

}).call(this);
