// Generated by CoffeeScript 1.10.0
(function() {
  importScripts('../lib/lz-string-1.3.3.js');

  self.addEventListener('message', function(e) {
    var data, out;
    data = e.data;
    out = LZString.compressToBase64(data);
    return self.postMessage(out);
  });

}).call(this);
