<?php

namespace AppBundle\Repository;

/**
 * DbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DbRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByParent(){

    }
}
