<?php

namespace AppBundle\Repository\User;

use Doctrine\ORM\EntityRepository;

/**
 * FennecUserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class FennecUserRepository extends EntityRepository
{
}
