<?php

namespace AppBundle\Repository\User;

use AppBundle\Entity\User\FennecUser;
use AppBundle\Entity\User\Permissions;
use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function getNumberOfProjects(FennecUser $user = null): int{
        if ($user === null) {
            return 0;
        }
        return count($this->getEntityManager()->getRepository(Permissions::class)->findBy(array(
            'user' => $user
        )));
    }

    public function getDataForUser(FennecUser $user) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('IDENTITY(project.user) AS userId', 'permissions.permission', 'project.id', 'project.importDate', 'project.importFilename', 'project.project')
            ->from('AppBundle\Entity\User\Permissions', 'permissions')
            ->innerJoin('AppBundle\Entity\User\Project', 'project', 'WITH', 'permissions.project = project.id')
            ->where('permissions.user = :userId')
            ->setParameter('userId', $user->getId());
        $query = $qb->getQuery();
        return $query->getResult();
    }

    public function getDataByProjectId($projectId) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('IDENTITY(project.user) AS userId', 'project.id', 'project.importDate', 'project.importFilename', 'project.project')
            ->from('AppBundle\Entity\User\Project', 'project')
            ->where('project.id = :projectId')
            ->setParameter('projectId', $projectId);
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
