<?php

namespace AppBundle\Repository\User;

use AppBundle\Entity\User\FennecUser;
use AppBundle\Entity\User\Permissions;
use AppBundle\Entity\User\WebuserData;
use Doctrine\ORM\EntityRepository;

/**
 * WebuserDataRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class WebuserDataRepository extends EntityRepository
{
    public function getNumberOfProjects(FennecUser $user = null): int{
        if ($user === null) {
            return 0;
        }
        return count($this->getEntityManager()->getRepository(Permissions::class)->findBy(array(
            'webuser' => $user
        )));
    }

    public function getDataForUser(FennecUser $user) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('IDENTITY(data.webuser) AS webuserId', 'p.permission', 'data.webuserDataId', 'data.importDate', 'data.importFilename', 'data.project')
            ->from('AppBundle\Entity\User\Permissions', 'p')
            ->innerJoin('AppBundle\Entity\User\WebuserData', 'data', 'WITH', 'p.webuserData = data.webuserDataId')
            ->where('p.webuser = :userId')
            ->setParameter('userId', $user->getId());
        $query = $qb->getQuery();
        return $query->getResult();
    }

    public function getDataByProjectId($projectId) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('IDENTITY(data.webuser) AS webuserId', 'data.webuserDataId', 'data.importDate', 'data.importFilename', 'data.project')
            ->from('AppBundle\Entity\User\WebuserData', 'data')
            ->where('data.webuserDataId = :projectId')
            ->setParameter('projectId', $projectId);
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
